fix: correct meson version retrieval and cleanup in Arch package setup

diff --git a/.github/workflows/package-repository.yml b/.github/workflows/package-repository.yml
--- a/.github/workflows/package-repository.yml
+++ b/.github/workflows/package-repository.yml
@@ -111,34 +111,34 @@ jobs:
           sudo mkdir -p /usr/local/meson
           sudo git clone https://github.com/mesonbuild/meson.git /usr/local/meson
           [ -f /usr/bin/meson ] && {
-            mver=<span class="math-inline">\(/usr/bin/meson --version\)
-            sudo mv /usr/bin/meson /usr/bin/meson-</span>{mver}
-          }
-          if [ -f /usr/local/meson/meson.py ]; then
+            mver=<span class="math-inline">\(/usr/bin/meson \-\-version\)
+            sudo mv /usr/bin/meson /usr/bin/meson\-</span>{mver}
+            }
+            if [ -f /usr/local/meson/meson.py ]; then
             sudo ln -s /usr/local/meson/meson.py /usr/bin/meson
-          else
-            echo "ERROR: cannot locate /usr/local/meson/meson.py"
+            else
+          echo "ERROR: cannot locate /usr/local/meson/meson.py"
             exit 1
-          fi
-
-          sudo rm -rf pacman
-          git clone https://gitlab.archlinux.org/pacman/pacman.git
-          cd pacman
-          meson setup -Ddoc=disabled build
-          ninja -C build
-
-          [ -d build ] || {
+            fi
+          
+            sudo rm -rf pacman
+            git clone https://gitlab.archlinux.org/pacman/pacman.git
+            cd pacman
+            meson setup -Ddoc=disabled build
+            ninja -C build
+          
+            [ -d build ] || {
             echo "Directory pacman/build does not exist. Exiting."
             exit 1
-          }
-          cd build
-          grep mirror scripts/libmakepkg/source/git.sh > /dev/null && {
+            }
+            cd build
+            grep mirror scripts/libmakepkg/source/git.sh > /dev/null && {
             cat scripts/libmakepkg/source/git.sh | sed -e "s/---mirror//" > /tmp/git$$
             cp /tmp/git$$ scripts/libmakepkg/source/git.sh
             rm -f /tmp/git$$
-          }
-
-          sudo meson install --no-rebuild --quiet
+            }
+          
+            sudo meson install --no-rebuild --quiet
 
       - name: Setup Package Directories
         run: |
